#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias gits="git status -s"

# wrap git with the hub command
eval "$(hub alias -s)"

# fix for using a carrot in commands, e.g. "git reset HEAD^^"
setopt localoptions nonomatch

# Update PATH for Postgres 11.
if [ -d "/usr/local/opt/postgresql@11/bin" ]; then export PATH=/usr/local/opt/postgresql@11/bin:$PATH; fi

# Update PATH for the Google Cloud SDK.
if [ -f "${ZDOTDIR:-$HOME}/src/google-cloud-sdk/path.zsh.inc" ]; then source "${ZDOTDIR:-$HOME}/src/google-cloud-sdk/path.zsh.inc"; fi

# Enable shell command completion for gcloud.
if [ -f "${ZDOTDIR:-$HOME}/src/google-cloud-sdk/completion.zsh.inc" ]; then source "${ZDOTDIR:-$HOME}/src/google-cloud-sdk/completion.zsh.inc"; fi
